name: Continuos Integration
on:
  push:
      branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TOKEN: ${{ secrets.TOKEN }}
      EMAIL: ${{ secrets.EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build without tests
        run: mvn clean install -DskipTests

      - name: Run Only Service Tests
        run: mvn -Dtest=*ServiceTest test