name: Continuos Integration
on:
  push:
      branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TOKEN: ${{ secrets.TOKEN }}
      EMAIL: ${{ secrets.EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn -Dtest=*ServiceTest test