name: Continuos Integration
on:
  push:
      branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn -Dtest=*ServiceTest test